### ISSUE TITLE
SO Dump

### ISSUE THREAD

**Issue by zdj1997** [muldon/dupPredictorRep#2]
I want to know where are the SO Dump of March 2017. 
Thanks!

**Comment by muldon** [comment]
We provide two links at the main page.

**Comment by muldon** [comment]
We provide two links at the main page.

**Comment by zdj1997** [comment]
> We provide two links at the main page.
But i could not find the two links or the main page.
Can you tell me directly? 
Thank you!

**Comment by muldon** [comment]
https://github.com/muldon/dupPredictorRep
Installing the app. section:
http://lascam.facom.ufu.br/companion/duplicatequestion/backup_so_march_2017_stemmed_stoped_ok.backup
