### ISSUE TITLE
some question

### ISSUE THREAD

**Issue by zdj1997** [muldon/dupPredictorRep#4]
I want to know whether this running interface lasts for dozens of hours？
I want to know whether I make some mistakes during the experiment?
Thank you  for your letter!
![running](https://user-images.githubusercontent.com/34509881/58367314-70316380-7f10-11e9-9ec9-d2daa3bb191c.png)

**Comment by muldon** [comment]
Only by this log it is hard to say. It looks like an error in your connection. We can discuss in more details by email, because other researchers could reproduce the approach. Send me an email with the complete log: estudantecomp@gmail.com
